#!/usr/bin/env bash
# Generate Sources/ogKit/BuildInfo.swift with the current git commit +
# build date. Called from Makefile before every build. The output file
# is .gitignored — `og --version` shows:
#   og 0.1.0 (abcd123, 2026-04-15)
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
OUT="$SCRIPT_DIR/../Sources/ogKit/BuildInfo.swift"

if command -v git >/dev/null 2>&1 && git -C "$SCRIPT_DIR" rev-parse --git-dir >/dev/null 2>&1; then
  COMMIT=$(git -C "$SCRIPT_DIR" rev-parse --short=7 HEAD 2>/dev/null || echo "unknown")
  DIRTY=""
  if ! git -C "$SCRIPT_DIR" diff --quiet 2>/dev/null || ! git -C "$SCRIPT_DIR" diff --cached --quiet 2>/dev/null; then
    DIRTY="+"
  fi
else
  COMMIT="unknown"
  DIRTY=""
fi

DATE=$(date -u +%Y-%m-%d)

cat > "$OUT" <<EOF
// Generated by scripts/generate-build-info.sh — do not edit by hand.
// .gitignored so every local / CI build stamps its own value.

public let ogBuildCommit = "$COMMIT$DIRTY"
public let ogBuildDate = "$DATE"
EOF
