#!/usr/bin/env bash
# Generate Sources/ogKit/BuildInfo.swift with the current git commit,
# build date, and CLI version. The version is read from the App's
# MARKETING_VERSION in orchardgrid-app.xcodeproj/project.pbxproj so a
# single bump (handled by release.yml on every release) drives both
# the .app's CFBundleShortVersionString and `og --version`.
#
# The output file is .gitignored — every local / CI build stamps its
# own value. `og --version` shows:
#   og v1.20.0 (abcd123, 2026-04-16)
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
OUT="$SCRIPT_DIR/../Sources/ogKit/BuildInfo.swift"
PBX="$SCRIPT_DIR/../../orchardgrid-app.xcodeproj/project.pbxproj"

if command -v git >/dev/null 2>&1 && git -C "$SCRIPT_DIR" rev-parse --git-dir >/dev/null 2>&1; then
  COMMIT=$(git -C "$SCRIPT_DIR" rev-parse --short=7 HEAD 2>/dev/null || echo "unknown")
  DIRTY=""
  if ! git -C "$SCRIPT_DIR" diff --quiet 2>/dev/null || ! git -C "$SCRIPT_DIR" diff --cached --quiet 2>/dev/null; then
    DIRTY="+"
  fi
else
  COMMIT="unknown"
  DIRTY=""
fi

DATE=$(date -u +%Y-%m-%d)

# Pull MARKETING_VERSION from the Xcode project so the CLI version
# tracks the App release tag automatically. Fall back to "0.0.0-dev"
# when invoked outside the orchardgrid-app workspace (e.g. someone
# building the CLI standalone via SPM checkout).
if [ -f "$PBX" ]; then
  VERSION=$(grep -m1 "MARKETING_VERSION = " "$PBX" \
    | sed 's/.*MARKETING_VERSION = \(.*\);.*/\1/' \
    | tr -d ' ')
else
  VERSION="0.0.0-dev"
fi
VERSION=${VERSION:-0.0.0-dev}

cat > "$OUT" <<EOF
// Generated by scripts/generate-build-info.sh — do not edit by hand.
// .gitignored so every local / CI build stamps its own value.

public let ogVersion = "$VERSION"
public let ogBuildCommit = "$COMMIT$DIRTY"
public let ogBuildDate = "$DATE"
EOF
